version: 
services:
  frontend:
    build:
      context:
    ports:
      - 80:80
  backend:
    build:
      context:
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - 5432:5432
    volumes:
      - 
  redis:
    image: redis:latest
    environment:
    ports:
      - 6379:6379
      