services:
  back:
    build:
      context: .
      ports:
        - 8080:8080
      depends_on:
        - postgres
        - redis
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: infinite
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    
volumes:
  postgres-data:
  redis-data: